backend:
  name: git-gateway
  branch: master
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
collections:
  name: "posts"
  label: "Posts"
  folder: "posts"
  create: true
  fields:
    - {label: "Layout", name: "layout", widget: hidden, default: "layouts/posts.njk"}
    - {label: "Title", name:"title", widget: "string" }
